### ISSUE TITLE
Неправильный отступ в моделях?

### ISSUE THREAD

**Issue by ilyaglar** [yandex-money/yandex-money-kit-django#2]
./manage.py migrate
Traceback (most recent call last):
  File "./manage.py", line 10, in <module>
    execute_from_command_line(sys.argv)
  File "/home/ilya/projects/oxy_landing/env/local/lib/python2.7/site-packages/django/core/management/__init__.py", line 338, in execute_from_command_line
    utility.execute()
  File "/home/ilya/projects/oxy_landing/env/local/lib/python2.7/site-packages/django/core/management/__init__.py", line 312, in execute
    django.setup()
  File "/home/ilya/projects/oxy_landing/env/local/lib/python2.7/site-packages/django/__init__.py", line 18, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "/home/ilya/projects/oxy_landing/env/local/lib/python2.7/site-packages/django/apps/registry.py", line 108, in populate
    app_config.import_models(all_models)
  File "/home/ilya/projects/oxy_landing/env/local/lib/python2.7/site-packages/django/apps/config.py", line 198, in import_models
    self.models_module = import_module(models_module_name)
  File "/usr/lib/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
  File "/home/ilya/projects/oxy_landing/env/local/lib/python2.7/site-packages/yandex_money/models.py", line 32
    MA = 'ma'
    ^
IndentationError: unexpected indent

**Comment by fed239** [comment]
Да, так и есть. Я пофиксил эту и ещё пару проблем, но Яндекс не аксептит пулл-реквест. Если хотите берите из моего репозитория: https://github.com/fed239/yandex-money-kit-django

**Comment by harabchuk** [comment]
Коллеги (из Яндекса) почему не почините хотя бы отступы в файле? Уверен, много людей, начинают с этого репозитория подключение яндекс денег и натыкаются на ошибку в отступах.
@fed239 спасибо за фиксы.

**Comment by ikarmanov** [comment]
Pull request принят. Спасибо за участие.
