### ISSUE TITLE
Win syncdb error

### ISSUE THREAD

**Issue by dronov-dmitry** [yandex-money/yandex-money-kit-django#31]
(win_venv) D:\MEGA\05_Python\05_django_flask\03_HVAC_API>python manage.py syncdb
['D:\\MEGA\\05_Python\\05_django_flask\\03_HVAC_API', 'D:\\MEGA\\05_Python\\05_django_flask\\03_HVAC_API', 'C:\\Python37\\python37.zip', 'C:\
\Python37\\DLLs', 'C:\\Python37\\lib', 'C:\\Python37', 'D:\\MEGA\\05_Python\\05_django_flask\\03_HVAC_API\\win_venv', 'D:\\MEGA\\05_Python\\0
5_django_flask\\03_HVAC_API\\win_venv\\lib\\site-packages', 'D:\\MEGA\\05_Python\\05_django_flask\\03_HVAC_API\\win_venv\\lib\\site-packages\
\setuptools-40.8.0-py3.7.egg', 'D:\\MEGA\\05_Python\\05_django_flask\\03_HVAC_API\\win_venv\\lib\\site-packages\\pip-19.0.3-py3.7.egg', 'D:\\
MEGA\\05_Python\\05_django_flask\\03_HVAC_API', 'D:\\MEGA\\05_Python\\05_django_flask\\03_HVAC_API']
Traceback (most recent call last):
  File "manage.py", line 22, in <module>
    main()
  File "manage.py", line 18, in main
    execute_from_command_line(sys.argv)
  File "D:\MEGA\05_Python\05_django_flask\03_HVAC_API\win_venv\lib\site-packages\django\core\management\__init__.py", line 401, in execute_fr
om_command_line
    utility.execute()
  File "D:\MEGA\05_Python\05_django_flask\03_HVAC_API\win_venv\lib\site-packages\django\core\management\__init__.py", line 377, in execute
    django.setup()
  File "D:\MEGA\05_Python\05_django_flask\03_HVAC_API\win_venv\lib\site-packages\django\__init__.py", line 24, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "D:\MEGA\05_Python\05_django_flask\03_HVAC_API\win_venv\lib\site-packages\django\apps\registry.py", line 114, in populate
    app_config.import_models()
  File "D:\MEGA\05_Python\05_django_flask\03_HVAC_API\win_venv\lib\site-packages\django\apps\config.py", line 211, in import_models
    self.models_module = import_module(models_module_name)
  File "C:\Python37\lib\importlib\__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "D:\MEGA\05_Python\05_django_flask\03_HVAC_API\win_venv\lib\site-packages\yandex_money\models.py", line 9, in <module>
    from django.utils.encoding import python_2_unicode_compatible
ImportError: cannot import name 'python_2_unicode_compatible' from 'django.utils.encoding' (D:\MEGA\05_Python\05_django_flask\03_HVAC_API\win
_venv\lib\site-packages\django\utils\encoding.py)

=======================================================

(win_venv) D:\MEGA\05_Python\05_django_flask\03_HVAC_API>pip freeze
asgiref==3.2.3
asn1crypto==1.3.0
certifi==2019.11.28
cffi==1.13.2
chardet==3.0.4
coincurve==13.0.0
Django==3.0.2
django-filter==2.2.0
django-yandex-money==1.1.3
djangorestframework==3.11.0
future==0.18.2
idna==2.8
jsonfield2==3.1.0
lxml==4.4.2
mypy-extensions==0.4.3
pbkdf2==1.3
pycparser==2.19
pytz==2019.3
requests==2.22.0
six==1.14.0
sqlparse==0.3.0
toolz==0.10.0
urllib3==1.25.7

(win_venv) D:\MEGA\05_Python\05_django_flask\03_HVAC_API>

**Comment by ostulov** [comment]
Добрый день!

Благодарю за сообщение о проблеме, подготовим решение.

**Comment by IPIvliev** [comment]
Такая же проблема. Как её решить?
